### PR TITLE
Replacing Deprecated Function

### PR DESCRIPTION
**Pull request by jeffreyCarlLong**
The function summarize_vars() has been deprecated and no longer works. It was uses in tables DT1, DT2, and TET1. A new function analyze_vars() is a renamed version of summarize_vars(). All occurrences of the deprecated function have been replaced in this pull request.

[https://github.com/search?q=repo%3Ainsightsengineering%2Fbiomarker-catalog%20summarize_vars&type=code](https://github.com/search?q=repo%3Ainsightsengineering%2Fbiomarker-catalog%20summarize_vars&type=code)

7 files are updated with 9 occurrences.

### CODE REVIEW

**Comment by jeffreyCarlLong** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jeffreyCarlLong** [comment]
This closes Biomarker Catalog GitHub Issue [https://github.com/insightsengineering/biomarker-catalog/issues/65](https://github.com/insightsengineering/biomarker-catalog/issues/65).

**Review by shajoezhu — APPROVED** [review]
lgtm! Thanks @jeffreyCarlLong

**Comment by jeffreyCarlLong** [comment]
Fixes https://github.com/insightsengineering/biomarker-catalog/issues/65

**Pull request merged**
